#-------------------------------
# General Site Settings


blurb: lorem ipususm dolor sit amet
email: lorem ipususm dolor sit amet
author: lorem ipususm dolor sit amet
bannerimage: lorem ipususm dolor sit amet
bannerimagealt: lorem ipususm dolor sit amet





  